<?php

function movie_database_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'movie_database/movie_database_css';
}

function movie_database_theme($existing, $type, $theme, $path) {
  return array(
    'temp' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'actormovie_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'actors_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    )
  );
}
